In [8]:
import pandas as pd
import exploration_utils
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.linear_model import LogisticRegression
from xgboost import XGBClassifier
from itertools import product
import json

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    average_precision_score
)

In [9]:
df = pd.read_csv('data/bank_marketing/bank_additional/bank_additional/bank-additional-full.csv', sep=';')

In [10]:
df.shape

(41188, 21)

In [11]:
df.head().T

,0,1,2,3,4
age,56,57,37,40,56
job,housemaid,services,services,admin.,services
marital,married,married,married,married,married
education,basic.4y,high.school,high.school,basic.6y,high.school
default,no,unknown,no,no,no
housing,no,no,yes,no,no
loan,no,no,no,no,yes
contact,telephone,telephone,telephone,telephone,telephone
month,may,may,may,may,may
day_of_week,mon,mon,mon,mon,mon
duration,261,149,226,151,307
campaign,1,1,1,1,1
pdays,999,999,999,999,999
previous,0,0,0,0,0
poutcome,nonexistent,nonexistent,nonexistent,nonexistent,nonexistent
emp.var.rate,1.1,1.1,1.1,1.1,1.1
cons.price.idx,93.994,93.994,93.994,93.994,93.994
cons.conf.idx,-36.4,-36.4,-36.4,-36.4,-36.4
euribor3m,4.857,4.857,4.857,4.857,4.857
nr.employed,5191.0,5191.0,5191.0,5191.0,5191.0
y,no,no,no,no,no

In [12]:
exploration_utils.missing_summary(df)

                missing_count  missing_percentage
age                         0                 0.0
job                         0                 0.0
marital                     0                 0.0
education                   0                 0.0
default                     0                 0.0
housing                     0                 0.0
loan                        0                 0.0
contact                     0                 0.0
month                       0                 0.0
day_of_week                 0                 0.0
duration                    0                 0.0
campaign                    0                 0.0
pdays                       0                 0.0
previous                    0                 0.0
poutcome                    0                 0.0
emp.var.rate                0                 0.0
cons.price.idx              0                 0.0
cons.conf.idx               0                 0.0
euribor3m                   0                 0.0
nr.employed                 0                 0.0
y                           0                 0.0

In [13]:
df.dtypes

age                 int64
job                   str
marital               str
education             str
default               str
housing               str
loan                  str
contact               str
month                 str
day_of_week           str
duration            int64
campaign            int64
pdays               int64
previous            int64
poutcome              str
emp.var.rate      float64
cons.price.idx    float64
cons.conf.idx     float64
euribor3m         float64
nr.employed       float64
y                     str
dtype: object

In [14]:
exploration_utils.find_unknown_like_values(df)

      column  count  percentage
0        job    330    0.801204
1    marital     80    0.194231
2  education   1731    4.202680
3    default   8597   20.872584
4    housing    990    2.403613
5       loan    990    2.403613

In [15]:
df["y"].value_counts(normalize=True) * 100

y
no     88.734583
yes    11.265417
Name: proportion, dtype: float64

In [16]:
X = df.drop(columns=["y", "duration"])
y = df["y"].map({
    "no": 0,
    "yes": 1
})
X_train, X_temp, y_train, y_temp = train_test_split(
    X,
    y,
    test_size=0.30,
    stratify=y,
    random_state=42
)

X_valid, X_test, y_valid, y_test = train_test_split(
    X_temp,
    y_temp,
    test_size=0.50,
    stratify=y_temp,
    random_state=42
)

print("Train:", X_train.shape, y_train.shape)
print("Validation:", X_valid.shape, y_valid.shape)
print("Test:", X_test.shape, y_test.shape)

Train: (28831, 19) (28831,)
Validation: (6178, 19) (6178,)
Test: (6179, 19) (6179,)

In [17]:
categorical_columns = X_train.select_dtypes(
    include=["object", "category", "str"]
).columns

numerical_columns = X_train.select_dtypes(
    include=["number"]
).columns

preprocessor = ColumnTransformer(
    transformers=[
        (
            "categorical",
            OneHotEncoder(handle_unknown="ignore"),
            categorical_columns
        ),
        (
            "numerical",
            StandardScaler(),
            numerical_columns
        )
    ]
)

In [18]:
X_train_processed = preprocessor.fit_transform(X_train)

X_valid_processed = preprocessor.transform(X_valid)
X_test_processed = preprocessor.transform(X_test)

# Logistic regression

In [19]:
logistic_model = LogisticRegression(
    max_iter=1000,
    random_state=42
)

logistic_model.fit(
    X_train_processed,
    y_train
)

LogisticRegression(max_iter=1000, random_state=42)

In [20]:
y_valid_pred_logreg = logistic_model.predict(X_valid_processed)
y_valid_proba_logreg = logistic_model.predict_proba(X_valid_processed)[:, 1]

metrics = {
    "accuracy": accuracy_score(y_valid, y_valid_pred_logreg),
    "precision": precision_score(y_valid, y_valid_pred_logreg),
    "recall": recall_score(y_valid, y_valid_pred_logreg),
    "f1": f1_score(y_valid, y_valid_pred_logreg),
    "roc_auc": roc_auc_score(y_valid, y_valid_proba_logreg),
    "pr_auc": average_precision_score(y_valid, y_valid_proba_logreg)
}

metrics

{'accuracy': 0.9011006798316608,
 'precision': 0.6923076923076923,
 'recall': 0.21982758620689655,
 'f1': 0.3336968375136314,
 'roc_auc': 0.8021599948839883,
 'pr_auc': 0.4700697725957582}

# XGBoost

In [21]:
xgb_model = XGBClassifier(
    n_estimators=300,
    max_depth=4,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    objective="binary:logistic",
    eval_metric="logloss",
    random_state=42
)

xgb_model.fit(
    X_train_processed,
    y_train,
    eval_set=[(X_valid_processed, y_valid)],
    verbose=False
)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.05, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=4, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=300, n_jobs=None,
              num_parallel_tree=None, ...)

In [22]:
y_valid_pred_xgb = xgb_model.predict(X_valid_processed)
y_valid_proba_xgb = xgb_model.predict_proba(X_valid_processed)[:, 1]

xgb_metrics = {
    "accuracy": accuracy_score(y_valid, y_valid_pred_xgb),
    "precision": precision_score(y_valid, y_valid_pred_xgb),
    "recall": recall_score(y_valid, y_valid_pred_xgb),
    "f1": f1_score(y_valid, y_valid_pred_xgb),
    "roc_auc": roc_auc_score(y_valid, y_valid_proba_xgb),
    "pr_auc": average_precision_score(y_valid, y_valid_proba_xgb)
}

xgb_metrics

{'accuracy': 0.9020718679184202,
 'precision': 0.6691449814126395,
 'recall': 0.25862068965517243,
 'f1': 0.37305699481865284,
 'roc_auc': 0.8141648005803738,
 'pr_auc': 0.4895400660752547}

# XGBoost tuning

In [23]:
param_grid = {
    "max_depth": [3, 4, 5],
    "learning_rate": [0.03, 0.05, 0.1],
    "n_estimators": [200, 300, 500]
}

results = []

for max_depth, learning_rate, n_estimators in product(
    param_grid["max_depth"],
    param_grid["learning_rate"],
    param_grid["n_estimators"]
):
    model = XGBClassifier(
        max_depth=max_depth,
        learning_rate=learning_rate,
        n_estimators=n_estimators,
        subsample=0.8,
        colsample_bytree=0.8,
        objective="binary:logistic",
        eval_metric="logloss",
        random_state=42
    )

    model.fit(
        X_train_processed,
        y_train,
        verbose=False
    )

    y_valid_proba = model.predict_proba(X_valid_processed)[:, 1]

    pr_auc = average_precision_score(
        y_valid,
        y_valid_proba
    )

    results.append({
        "max_depth": max_depth,
        "learning_rate": learning_rate,
        "n_estimators": n_estimators,
        "pr_auc": pr_auc
    })

tuning_results = pd.DataFrame(results).sort_values(
    "pr_auc",
    ascending=False
)

tuning_results

    max_depth  learning_rate  n_estimators    pr_auc
9           4           0.03           200  0.493698
12          4           0.05           200  0.493613
18          5           0.03           200  0.493146
3           3           0.05           200  0.492662
5           3           0.05           500  0.492566
11          4           0.03           500  0.492418
10          4           0.03           300  0.492351
4           3           0.05           300  0.491802
19          5           0.03           300  0.491388
15          4           0.10           200  0.491083
20          5           0.03           500  0.491077
21          5           0.05           200  0.490599
13          4           0.05           300  0.489540
0           3           0.03           200  0.489472
1           3           0.03           300  0.489347
16          4           0.10           300  0.489318
2           3           0.03           500  0.488896
14          4           0.05           500  0.488882
22          5           0.05           300  0.487734
17          4           0.10           500  0.487035
6           3           0.10           200  0.486836
8           3           0.10           500  0.485450
7           3           0.10           300  0.485083
23          5           0.05           500  0.484900
24          5           0.10           200  0.483021
25          5           0.10           300  0.479374
26          5           0.10           500  0.474871

### Merge train and validation set and preprocess them

In [24]:
X_train_final = pd.concat([X_train, X_valid])
y_train_final = pd.concat([y_train, y_valid])

categorical_columns = X_train_final.select_dtypes(
    include=["object", "category", "str"]
).columns

numerical_columns = X_train_final.select_dtypes(
    include=["number"]
).columns

xgb_preprocessor_final = ColumnTransformer(
    transformers=[
        (
            "categorical",
            OneHotEncoder(handle_unknown="ignore"),
            categorical_columns
        ),
        (
            "numerical",
            StandardScaler(),
            numerical_columns
        )
    ]
)

X_train_final_processed = xgb_preprocessor_final.fit_transform(
    X_train_final
)

X_test_final_processed = xgb_preprocessor_final.transform(
    X_test
)

In [25]:
final_model = XGBClassifier(
    max_depth=4,
    learning_rate=0.03,
    n_estimators=200,
    subsample=0.8,
    colsample_bytree=0.8,
    objective="binary:logistic",
    eval_metric="logloss",
    random_state=42
)

final_model.fit(
    X_train_final_processed,
    y_train_final
)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.03, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=4, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=200, n_jobs=None,
              num_parallel_tree=None, ...)

In [26]:
y_test_pred = final_model.predict(X_test_final_processed)
y_test_proba = final_model.predict_proba(X_test_final_processed)[:, 1]

final_metrics = {
    "accuracy": accuracy_score(y_test, y_test_pred),
    "precision": precision_score(y_test, y_test_pred),
    "recall": recall_score(y_test, y_test_pred),
    "f1": f1_score(y_test, y_test_pred),
    "roc_auc": roc_auc_score(y_test, y_test_proba),
    "pr_auc": average_precision_score(y_test, y_test_proba)
}

final_metrics

{'accuracy': 0.9019258779737822,
 'precision': 0.6956521739130435,
 'recall': 0.22988505747126436,
 'f1': 0.34557235421166305,
 'roc_auc': 0.8117371929118425,
 'pr_auc': 0.4862312324392072}

In [27]:
with open("final_metrics.json", "w") as file:
    json.dump(final_metrics, file, indent=4)